Projeto.Web/Areas/Agenda/Controllers/TarefaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Projeto.Web.Areas.Agenda.Models;
using Projeto.DAL.Entities;
using Projeto.DAL.Persistence;
using Projeto.Web.Models;
using Newtonsoft.Json;
using Microsoft.Reporting.WebForms;

namespace Projeto.Web.Areas.Agenda.Controllers
{
    [Authorize]
    public class TarefaController : Controller
    {
        // GET: /Agenda/Tarefa/Index
        public ActionResult Index()
        {
            return View();
        }

        // GET: /Agenda/Tarefa/Cadastro
        public ActionResult Cadastro()
        {
            return View();
        }

        // GET: /Agenda/Tarefa/Consulta
        public ActionResult Consulta()
        {
            return View();
        }



        // POST: /Agenda/Tarefa/CadastrarTarefa
        [HttpPost] //recebe requisições do tipo POST
        [ValidateAntiForgeryToken] //requerer ticket de acesso
        public ActionResult CadastrarTarefa(TarefaViewModelCadastro model)
        {
            //verificar se os dados da model passaram na validação..
            if(ModelState.IsValid)
            {
                try
                {
                    //Resgatar o usuario to ticket..
                    string ticket = HttpContext.User.Identity.Name;
                    UsuarioAutenticado auth = JsonConvert.DeserializeObject<UsuarioAutenticado>(ticket);

                    Tarefa t = new Tarefa(); //entidade..
                    t.Titulo = model.Titulo;
                    t.Descricao = model.Descricao;
                    t.DataHora = model.DataHora;
                    t.Status = model.Status;
                    t.Tipo = model.Tipo;
                    t.IdUsuario = auth.IdUsuario; //foreign key..

                    TarefaDal d = new TarefaDal();
                    d.Insert(t); //gravando..

                    ViewBag.Mensagem = "Tarefa " + t.Titulo + ", cadastrado com sucesso.";
                    ModelState.Clear(); //limpar o conteudo do formulário..
                }
                catch(Exception e)
                {
                    //imprimindo mensagem de erro..
                    ViewBag.Mensagem = e.Message;
                }
            }

            return View("Cadastro"); //nome da página..
        }


        //método para consultar as tarefas...
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConsultarTarefas(TarefaViewModelConsulta model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    //trazer o usuario autenticado..
                    string ticket = HttpContext.User.Identity.Name;
                    UsuarioAutenticado auth = JsonConvert.DeserializeObject<UsuarioAutenticado>(ticket);
                    
                    TarefaDal d = new TarefaDal(); //persistencia..
                    model.Tarefas = d.Find(auth.IdUsuario, model.DataInicio, model.DataFim);
                    
                    if(model.Tarefas.Count > 0)
                    {
                        ViewBag.Mensagem = "Consulta realizada com sucesso.";

                        //armazenar as datas em sessão...
                        Session.Add("datainicio", model.DataInicio);
                        Session.Add("datafim", model.DataFim);
                    }
                    else
                    {
                        ViewBag.Mensagem = "Nenhuma tarefa foi encontrada.";
                    }
                }
            }
            catch(Exception e)
            {
                ViewBag.Mensagem = e.Message;
            }

            return View("Consulta", model);
        }


        [HttpGet]
        public ActionResult ExcluirTarefa(int id)
        {
            try
            {
                string ticket = HttpContext.User.Identity.Name;
                UsuarioAutenticado auth = JsonConvert.DeserializeObject<UsuarioAutenticado>(ticket);

                //buscar a tarefa no banco de dados..
                TarefaDal d = new TarefaDal(); //persistencia..
                Tarefa t = d.FindById(id);

                //verificar se a tarefa pertence ao usuario logado..
                if(t.IdUsuario == auth.IdUsuario)
                {
                    d.Delete(t); //excluir a tarefa..
                    ViewBag.Mensagem = "Tarefa " + t.Titulo + ", excluido com sucesso.";
                }
            }
            catch(Exception e)
            {
                ViewBag.Mensagem = e.Message;
            }

            return View("Consulta");
        }



        //método para gerar o relatorio de tarefas da agenda..
        [HttpPost] //recebe requisição do tipo POST
        public ActionResult GerarRelatorio(string Tipo)
        {
            try
            {
                //resgatar as datas que estão em sessão...
                DateTime DataInicio = (DateTime) Session["datainicio"];
                DateTime DataFim = (DateTime) Session["datafim"];

                //resgatar o usuario gravado no ticket..
                string ticket = HttpContext.User.Identity.Name;
                UsuarioAutenticado auth = JsonConvert.DeserializeObject<UsuarioAutenticado>(ticket);

                //consultar as tarefas..
                TarefaDal d = new TarefaDal(); //persistencia..
                List<Tarefa> lista = d.Find(auth.IdUsuario, DataInicio, DataFim);

                //Gerando o relatório...
                //1º) Caminho do relatório...
                string path = HttpContext.Server.MapPath("/Reports/RelatorioAgenda.rdlc");

                //2º) Parametros do relatório...
                ReportParameter[] parametros = new ReportParameter[3];
                parametros[0] = new ReportParameter("DataInicio", DataInicio.ToString("ddd dd/MM/yyyy"));
                parametros[1] = new ReportParameter("DataTermino", DataFim.ToString("ddd dd/MM/yyyy"));
                parametros[2] = new ReportParameter("Usuario", auth.Nome);

                //3º) Gerar o relatório...
                ReportViewer relatorio = new ReportViewer();
                relatorio.LocalReport.ReportPath = path; //caminho do relatório..
                relatorio.LocalReport.DataSources.Add(new ReportDataSource("DataSetAgenda", lista));
                relatorio.LocalReport.SetParameters(parametros);

                switch(Int32.Parse(Tipo))
                {
                    case 1: //PDF                       
                        return File(relatorio.LocalReport.Render("PDF"), 
                            "application/pdf", "agenda.pdf");

                    case 2: //Word
                        return File(relatorio.LocalReport.Render("WORD"), 
                            "application/msword", "agenda.doc");

                    case 3: //Excel
                        return File(relatorio.LocalReport.Render("EXCEL"), 
                            "application/excel", "agenda.xls");

                    default:
                        throw new Exception("Erro. Opção inválida.");
                }
            }
            catch(Exception e)
            {
                //exibir mensagem de erro..
                ViewBag.Mensagem = e.Message;
            }

            return View("Consulta"); //nome da página..
        }


	}
}

Projeto.Web/Areas/Agenda/Views/Tarefa/Cadastro.cshtml
@model Projeto.Web.Areas.Agenda.Models.TarefaViewModelCadastro

@{
    ViewBag.Title = "Cadastro";
    Layout = "~/Areas/Agenda/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("CadastrarTarefa", "Tarefa", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <h4>Cadastro de Tarefas</h4>
        <a href="/Agenda/Tarefa/Index">Voltar</a>
        <hr />

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo)
                @Html.ValidationMessageFor(model => model.Titulo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao)
                @Html.ValidationMessageFor(model => model.Descricao)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataHora, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DataHora, new { @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.DataHora)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, "- Escolha uma Opção -")
                @Html.ValidationMessageFor(model => model.Status)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Tipo, "- Escolha uma Opção -")
                @Html.ValidationMessageFor(model => model.Tipo)
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar Tarefa" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @ViewBag.Mensagem
</div>

Projeto.Web/Areas/Agenda/Views/Tarefa/Consulta.cshtml
@model Projeto.Web.Areas.Agenda.Models.TarefaViewModelConsulta

@{
    ViewBag.Title = "Consulta";
    Layout = "~/Areas/Agenda/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("ConsultarTarefas", "Tarefa", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <h4>Consulta de Tarefas na Agenda</h4>
        <a href="/Agenda/Tarefa/Index">Voltar</a>
        <hr />

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.DataInicio, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DataInicio, new { @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.DataInicio)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataFim, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DataFim, new { @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.DataFim)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Consultar Tarefas" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @ViewBag.Mensagem
</div>


<!-- Verificar se a lista de tarefas possui conteudo -->
@if(Model != null && Model.Tarefas != null && Model.Tarefas.Count > 0)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Código</th>
                <th>Titulo da Tarefa</th>
                <th>Data da Tarefa</th>
                <th>Status</th>
                <th>Tipo</th>
                <th>Descrição</th>
                <th>Operações</th>
            </tr>
        </thead>
        <tbody>

            @foreach(var t in Model.Tarefas)
            {
                <tr>
                    <td> @t.IdTarefa </td>
                    <td> @t.Titulo </td>
                    <td> @t.DataHora </td>
                    <td> @t.Status </td>
                    <td> @t.Tipo </td>
                    <td> @t.Descricao </td>
                    <td> 
                        @Html.ActionLink("Excluir", "ExcluirTarefa",
                                         new { id = @t.IdTarefa },
                                         new { @class = "btn btn-danger btn-sm" }) 
                    </td>
                </tr>
            }

        </tbody>
        <tfoot>
            <tr>
                <td colspan="7"> Quantidade de Tarefas: @Model.Tarefas.Count </td>
            </tr>
        </tfoot>
    </table>
    
    <!-- Área de formulário HTML -->
    <form method="post" action="/Agenda/Tarefa/GerarRelatorio">
        
        Exportar dados da Agenda:
        <select name="Tipo">
            <option value="0">- Escolha uma Opção -</option>
            <option value="1">PDF</option>
            <option value="2">Word</option>
            <option value="3">Excel</option>
        </select>

        <input type="submit" value="Gerar Relatório"/>

    </form>
    
}

Projeto.Web/Areas/Agenda/Views/Tarefa/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Agenda/Views/Shared/Layout.cshtml";
}

<h4>Página Principal</h4>

<p>
    Selecione a ação desejada:
</p>

<ul>
    <li> <a href="/Agenda/Tarefa/Cadastro">Cadastrar Nova Tarefa</a> </li>
    <li> <a href="/Agenda/Tarefa/Consulta">Consultar Agenda</a> </li>
</ul>